version: '3.8'

services:
  app:
    image: ramana2003/nodeimage:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
